server:
  port: 9002
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: customer-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000 # 5s
      request-read-timeout: 5000 # 5s
      fail-fast: false # In production, set to true
      retry:
        max-attempts: 6
        initial-interval: 1000 # 1s
        max-interval: 2000 # 2s
        multiplier: 1.1
  datasource:
    username: root
    password: password
    url: jdbc:oracle:thin:@//localhost:47162/ORCLCDB.localdomain
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5
      driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
           issuer-uri: http://localhost:8080/realms/KDBS
  flyway:
    enabled: false



logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

info:
  system: Office Service

management:
  endpoints:
    web:
      exposure:
        include: refresh
keycloak:
  realm: KDBS
  url: http://localhost:8080
  user: kdbs_user
  password: password
  client:
    id: edge-service
    secret: kdbs-keycloak-secret
