server:
  port: 8085
spring:
  application:
    name: customer-command
  lifecycle:
    timeout-per-shutdown-phase: 15s

springdoc:
  swagger-ui:
    path: /openapi/swagger-ui.html
  api-docs:
    path: /openapi/v3/api-docs
  packages-to-scan: ir.negah.bank
  pathsToMatch: /**

axon:
  eventhandling:
    processors:
      name:
        mode: tracking
  axonserver:
    enabled: true
    servers: axonserver
